{% set name = "fastapi-azure-auth" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1c1cd41bc4ca2bce598b5c30695e430ebfa7a5e5b362fbca2d4dfbc3c10fc7a4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - cryptography >=38.0.3
    - fastapi >0.68.0
    - httpx >0.18.2
    - pip
    - poetry
    - pyjwt
    - python

  run:
    - cryptography >=38.0.3
    - fastapi >0.68.0
    - httpx >0.18.2
    - pyjwt
    - python

test:
  imports:
    - fastapi_azure_auth

about:
  home: https://github.com/intility/fastapi-azure-auth
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Easy and secure implementation of Azure AD for your FastAPI APIs
  doc_url: https://github.com/intility/fastapi-azure-auth
  dev_url: https://github.com/intility/fastapi-azure-auth

extra:
  recipe-maintainers:
    - rars
